// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RejestrKontaktowv2.Models;

#nullable disable

namespace RejestrKontaktowv2.Migrations
{
    [DbContext(typeof(RejestrKontaktowv2DbContext))]
    [Migration("20250604102121_whot")]
    partial class whot
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RejestrKontaktowv2.Models.Osoba", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("adres")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("imie")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nazwisko")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nr_tel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("Osoby");

                    b.HasData(
                        new
                        {
                            id = 1,
                            adres = "Warszawa",
                            email = "kur@gmail.com",
                            imie = "Hubert",
                            nazwisko = "Kurowski",
                            nr_tel = "111111111"
                        },
                        new
                        {
                            id = 2,
                            adres = "Podgorze Gazdy",
                            email = "barz@gmail.com",
                            imie = "Aleksander",
                            nazwisko = "Barzyczak",
                            nr_tel = "222222222"
                        },
                        new
                        {
                            id = 3,
                            adres = "Ciechocinek",
                            email = "bess@gmail.com",
                            imie = "Wiktor",
                            nazwisko = "Bessert",
                            nr_tel = "333333333"
                        },
                        new
                        {
                            id = 4,
                            adres = "Saperowice",
                            email = "chu@gmail.com",
                            imie = "Marcin",
                            nazwisko = "Chuchla",
                            nr_tel = "444444444"
                        },
                        new
                        {
                            id = 5,
                            adres = "Pabianice",
                            email = "daw@gmail.com",
                            imie = "Dawid",
                            nazwisko = "Jasper",
                            nr_tel = "1"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
